# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi_eta_struct.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='multi_eta_struct.proto',
  package='MultiEtaInfo',
  syntax='proto3',
  serialized_pb=_b('\n\x16multi_eta_struct.proto\x12\x0cMultiEtaInfo\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\":\n\x0bTrafficInfo\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\x05\"L\n\rRouteLocation\x12\x0f\n\x07link_id\x18\x01 \x01(\x05\x12*\n\ron_link_point\x18\x02 \x01(\x0b\x32\x13.MultiEtaInfo.Point\"Z\n\x08LinkInfo\x12\x0f\n\x07link_id\x18\x01 \x01(\x05\x12\x10\n\x08reversed\x18\x02 \x01(\x05\x12+\n\x08traffics\x18\x03 \x03(\x0b\x32\x19.MultiEtaInfo.TrafficInfo\"%\n\x08\x44uration\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03\x65ta\x18\x02 \x01(\x05\"6\n\nRpDuration\x12(\n\x08\x64uration\x18\x01 \x03(\x0b\x32\x16.MultiEtaInfo.Duration\"U\n\x0cResponseData\x12\x16\n\x0emap_db_version\x18\x01 \x01(\t\x12-\n\x0brp_duration\x18\x02 \x03(\x0b\x32\x18.MultiEtaInfo.RpDuration\"\xe8\x01\n\x07Request\x12+\n\x06origin\x18\x01 \x01(\x0b\x32\x1b.MultiEtaInfo.RouteLocation\x12\x30\n\x0b\x64\x65stination\x18\x02 \x01(\x0b\x32\x1b.MultiEtaInfo.RouteLocation\x12,\n\x07rpPoint\x18\x03 \x03(\x0b\x32\x1b.MultiEtaInfo.RouteLocation\x12\x0f\n\x07linkIdx\x18\x04 \x03(\x05\x12\'\n\x07rpLinks\x18\x05 \x03(\x0b\x32\x16.MultiEtaInfo.LinkInfo\x12\x16\n\x0emap_db_version\x18\x06 \x01(\t\"Q\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12(\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1a.MultiEtaInfo.ResponseDatab\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='MultiEtaInfo.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MultiEtaInfo.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='MultiEtaInfo.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=69,
)


_TRAFFICINFO = _descriptor.Descriptor(
  name='TrafficInfo',
  full_name='MultiEtaInfo.TrafficInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MultiEtaInfo.TrafficInfo.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='MultiEtaInfo.TrafficInfo.speed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='MultiEtaInfo.TrafficInfo.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=129,
)


_ROUTELOCATION = _descriptor.Descriptor(
  name='RouteLocation',
  full_name='MultiEtaInfo.RouteLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link_id', full_name='MultiEtaInfo.RouteLocation.link_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='on_link_point', full_name='MultiEtaInfo.RouteLocation.on_link_point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=207,
)


_LINKINFO = _descriptor.Descriptor(
  name='LinkInfo',
  full_name='MultiEtaInfo.LinkInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link_id', full_name='MultiEtaInfo.LinkInfo.link_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reversed', full_name='MultiEtaInfo.LinkInfo.reversed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='traffics', full_name='MultiEtaInfo.LinkInfo.traffics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=299,
)


_DURATION = _descriptor.Descriptor(
  name='Duration',
  full_name='MultiEtaInfo.Duration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MultiEtaInfo.Duration.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eta', full_name='MultiEtaInfo.Duration.eta', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=338,
)


_RPDURATION = _descriptor.Descriptor(
  name='RpDuration',
  full_name='MultiEtaInfo.RpDuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='MultiEtaInfo.RpDuration.duration', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=394,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='ResponseData',
  full_name='MultiEtaInfo.ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_db_version', full_name='MultiEtaInfo.ResponseData.map_db_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rp_duration', full_name='MultiEtaInfo.ResponseData.rp_duration', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=481,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='MultiEtaInfo.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='MultiEtaInfo.Request.origin', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destination', full_name='MultiEtaInfo.Request.destination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpPoint', full_name='MultiEtaInfo.Request.rpPoint', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linkIdx', full_name='MultiEtaInfo.Request.linkIdx', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpLinks', full_name='MultiEtaInfo.Request.rpLinks', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map_db_version', full_name='MultiEtaInfo.Request.map_db_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=716,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='MultiEtaInfo.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='MultiEtaInfo.Response.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='MultiEtaInfo.Response.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='MultiEtaInfo.Response.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=799,
)

_ROUTELOCATION.fields_by_name['on_link_point'].message_type = _POINT
_LINKINFO.fields_by_name['traffics'].message_type = _TRAFFICINFO
_RPDURATION.fields_by_name['duration'].message_type = _DURATION
_RESPONSEDATA.fields_by_name['rp_duration'].message_type = _RPDURATION
_REQUEST.fields_by_name['origin'].message_type = _ROUTELOCATION
_REQUEST.fields_by_name['destination'].message_type = _ROUTELOCATION
_REQUEST.fields_by_name['rpPoint'].message_type = _ROUTELOCATION
_REQUEST.fields_by_name['rpLinks'].message_type = _LINKINFO
_RESPONSE.fields_by_name['data'].message_type = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['TrafficInfo'] = _TRAFFICINFO
DESCRIPTOR.message_types_by_name['RouteLocation'] = _ROUTELOCATION
DESCRIPTOR.message_types_by_name['LinkInfo'] = _LINKINFO
DESCRIPTOR.message_types_by_name['Duration'] = _DURATION
DESCRIPTOR.message_types_by_name['RpDuration'] = _RPDURATION
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.Point)
  ))
_sym_db.RegisterMessage(Point)

TrafficInfo = _reflection.GeneratedProtocolMessageType('TrafficInfo', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICINFO,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.TrafficInfo)
  ))
_sym_db.RegisterMessage(TrafficInfo)

RouteLocation = _reflection.GeneratedProtocolMessageType('RouteLocation', (_message.Message,), dict(
  DESCRIPTOR = _ROUTELOCATION,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.RouteLocation)
  ))
_sym_db.RegisterMessage(RouteLocation)

LinkInfo = _reflection.GeneratedProtocolMessageType('LinkInfo', (_message.Message,), dict(
  DESCRIPTOR = _LINKINFO,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.LinkInfo)
  ))
_sym_db.RegisterMessage(LinkInfo)

Duration = _reflection.GeneratedProtocolMessageType('Duration', (_message.Message,), dict(
  DESCRIPTOR = _DURATION,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.Duration)
  ))
_sym_db.RegisterMessage(Duration)

RpDuration = _reflection.GeneratedProtocolMessageType('RpDuration', (_message.Message,), dict(
  DESCRIPTOR = _RPDURATION,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.RpDuration)
  ))
_sym_db.RegisterMessage(RpDuration)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEDATA,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.ResponseData)
  ))
_sym_db.RegisterMessage(ResponseData)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'multi_eta_struct_pb2'
  # @@protoc_insertion_point(class_scope:MultiEtaInfo.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
